#!/bin/bash

echo "* Generating coins..."
sleep 2

dash-cli -conf=/etc/conf/node-1/dash.conf generate 101 > /dev/null
dash-cli -conf=/etc/conf/node-1/dash.conf generate 101 > /dev/null

ADDRESS=`dash-cli -conf=/etc/conf/node-1/dash.conf getnewaddress shop`
dash-cli -conf=/etc/conf/node-1/dash.conf sendtoaddress "$ADDRESS" 50

echo "sent generated coins to $ADDRESS"

ADDRESS=`dash-cli -conf=/etc/conf/node-2/dash.conf getnewaddress customer`
dash-cli -conf=/etc/conf/node-1/dash.conf sendtoaddress "$ADDRESS" 50

echo "sent generated coins to $ADDRESS"


echo "* Generating another coins..."
dash-cli -conf=/etc/conf/node-1/dash.conf generate 101  > /dev/null
echo "* Done!"

sleep 2

s6-svc -d /var/run/s6/services/generate