#!/bin/sh

echo "* Dashd node 1..."
exec /usr/bin/dashd \
    --printtoconsole \
    -datadir=/data/node-1 \
    -conf=/etc/conf/node-1/dash.conf \
    -server \
    -walletnotify='/usr/bin/dash-cli -conf=/etc/conf/node-1/dash.conf gettransaction %s | tr "\n" " " | sed "s/$/\n/"  > /var/run/dashd/events-in' \
    -blocknotify='echo %s > /var/run/dashd/events-in'
